version: '3'
services:
  cram-binder:
    image: coai:binderhub
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    # set group id of the host machine, so we can edit contents of the mounted volumes in the jupyterlab
    user: "jovyan:${GID}"
    # user: root
    working_dir: /home/jovyan
    entrypoint: /home/jovyan/COAI/binder/entrypoint.sh
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser
    ports:
      - 8888:8888
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - ../:/home/jovyan/COAI:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw